name: Tempmesh API Deploy

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

  workflow_dispatch:

jobs:
  test:
    name: Run Unit & Integration Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install

      - name: Run tests
        run: bun test

  deploy:
    name: Deploy over SSH
    runs-on: ubuntu-latest
    needs: test # Somente executa se passou os testes
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Copy files with SSH
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "-rltgoDzvO --delete"
          SOURCE: "./"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.TARGET_DIR }}
          EXCLUDE: "/node_modules/, **.env, .env.local, .gitignore, .git/, .github/, .vscode/"
          SCRIPT_BEFORE: |
            echo "===> Starting deployment"
            sudo systemctl stop nginx
            echo "|||| Running halt.sh..."
            cd ${{ secrets.TARGET_DIR }}
            .scripts/halt.sh
          SCRIPT_AFTER: |
            whoami
            ls -al
            echo $RSYNC_STDOUT
            cd ${{ secrets.TARGET_DIR }}
            sudo systemctl start nginx
            echo "|||| Running run.sh..."
            .scripts/run.sh
            echo "===> Finished deployment"